// Paste this entire content into model/person_detect_model.h

#pragma once

// This header file is generated by dl-model-tools, convert from yolofastest-1.1_person.onnx
// For more information, please see https://github.com/espressif/dl-model-tools
#include "dl_tool.hpp"
#include "dl_layer_base.hpp"
#include "dl_layer_conv2d.hpp"
#include "dl_layer_depthwise_conv2d.hpp"
#include "dl_layer_add.hpp"
#include "dl_layer_leaky_relu.hpp"
#include "dl_layer_max_pool2d.hpp"
#include "dl_layer_upsample.hpp"
#include "dl_layer_concat.hpp"
#include "dl_layer_reshape.hpp"

#define PERSON_DETECT_MODEL_INPUT_MEAN (0)
#define PERSON_DETECT_MODEL_INPUT_STD (255.0)

// extern const dl_matrix3du_t* get_person_detect_model_input();
// extern const float* get_person_detect_model_coefficient();

const dl_matrix3du_t* get_person_detect_model_input();
const float* get_person_detect_model_coefficient();